# Generated by Django 2.0.4 on 2018-04-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('name', models.CharField(choices=[('A', 'StockA'), ('B', 'StockB'), ('C', 'StockC'), ('D', 'StockD'), ('E', 'StockE')], max_length=1, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('stockA', models.IntegerField()),
                ('stockB', models.IntegerField()),
                ('stockC', models.IntegerField()),
                ('stockD', models.IntegerField()),
                ('stockE', models.IntegerField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
