# Generated by Django 2.0.4 on 2018-04-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxnDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnID', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=10)),
                ('stock', models.CharField(choices=[('A', 'StockA'), ('B', 'StockB'), ('C', 'StockC'), ('D', 'StockD'), ('E', 'StockE')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserExt')),
            ],
        ),
    ]
